packages:
  - .

minimumReleaseAge: 2880 # 48 hrs
onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - sharp

overrides:
  devalue: 5.8.1
  esbuild: 0.25.0
  fast-xml-parser: 5.7.0
  file-type: 21.3.4
  lodash: 4.18.0
  tmp: 0.2.5
  undici: 6.24.1
  yaml: 2.8.3
